name: momma-me-ecommerce
region: nyc
services:
  - name: web
    source_dir: /
    github:
      repo: iamsnh1/momma-me
      branch: main
      deploy_on_push: true
    build_command: npm run build
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"

